# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Personal Blog of Karthik Bala
tagline:             ''
description:         'yo'
url:                 http://karthiksthings.com
baseurl:             ''
paginate:            5
paginate_path:       "page:num"

# About/contact
author:
  name:              Karthik Bala
  url:               karthiksthings.com
  email:             karthikbala444@gmail.com

# Custom vars
version:             1.0.0

# Gems
gems: [jekyll-paginate]

